# Generated by Django 5.0.1 on 2024-02-28 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0003_customuser_facebook_url_customuser_telegram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='facebook url'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='telegram url'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='whatsapp url'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('liked_products', models.ManyToManyField(blank=True, to='store.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
