# Generated by Django 5.0.1 on 2024-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ordersuperuser',
            field=models.BooleanField(default=False),
        ),
    ]
