# Generated by Django 5.0.1 on 2024-02-29 04:32

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=django_quill.fields.QuillField(),
        ),
    ]
