# Generated by Django 5.0.1 on 2024-03-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sizevariation_color_delete_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
