# Generated by Django 5.0.1 on 2024-03-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
