# Generated by Django 4.2.15 on 2024-08-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
