# Generated by Django 5.0.1 on 2024-02-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertizement', '0003_alter_advertizementfirst_advertizement_first_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon_image', models.ImageField(blank=True, null=True, upload_to='images/advertizements')),
            ],
        ),
    ]
