# Generated by Django 5.0.1 on 2024-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertizement', '0004_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertizementfirst',
            name='advertizement_first_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertizementsecond',
            name='advertizement_second_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertizementthird',
            name='advertizement_third_url',
            field=models.URLField(blank=True),
        ),
    ]
