# Generated by Django 5.0.1 on 2024-01-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='images/contacts'),
        ),
    ]
