# Generated by Django 5.0.1 on 2024-01-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_contact_company_description_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Footer',
        ),
    ]
