# Generated by Django 5.0.1 on 2024-02-08 12:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_rename_logo_image_footer_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='footer',
            name='company_main_page_title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/contacts'),
        ),
        migrations.AddField(
            model_name='footer',
            name='main_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/contacts'),
        ),
        migrations.AddField(
            model_name='footer',
            name='nav_company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/contacts'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
